
import { Juz } from './types';

export const JUZ_DATA: Juz[] = [
  { number: 1, nameArabic: "الٓمّٓ", nameEnglish: "Alif Laam Meem", startSurah: "Al-Fatihah" },
  { number: 2, nameArabic: "سَيَقُوۡلُ", nameEnglish: "Sayaqūl", startSurah: "Al-Baqarah" },
  { number: 3, nameArabic: "تِلۡكَ الرُّسُلُ", nameEnglish: "Tilka’r-Rusul", startSurah: "Al-Baqarah" },
  { number: 4, nameArabic: "لَنۡ تَنَالُوا", nameEnglish: "Lan Tanālū", startSurah: "Al-Imran" },
  { number: 5, nameArabic: "وَّالۡمُحۡصَنٰتُ", nameEnglish: "Wa’l-Muḥṣanāt", startSurah: "An-Nisa" },
  { number: 6, nameArabic: "لَا يُحِبُّ اللّٰهُ", nameEnglish: "Lā Yuḥibbu’llāh", startSurah: "An-Nisa" },
  { number: 7, nameArabic: "وَاِذَا سَمِعُوۡا", nameEnglish: "Wa Idhā Samiʿū", startSurah: "Al-Ma'idah" },
  { number: 8, nameArabic: "وَلَوۡ اَنَّـنَا", nameEnglish: "Wa Law Annanā", startSurah: "Al-An'am" },
  { number: 9, nameArabic: "قَالَ الۡمَلَاُ", nameEnglish: "Qāla’l-Mala’u", startSurah: "Al-A'raf" },
  { number: 10, nameArabic: "وَاعۡلَمُوۡۤا", nameEnglish: "Wa’ʿlamū", startSurah: "Al-Anfal" },
  { number: 11, nameArabic: "يَعۡتَذِرُوۡنَ", nameEnglish: "Yaʿtadhirūn", startSurah: "At-Tawbah" },
  { number: 12, nameArabic: "وَمَا مِنۡ دَآ بَّةٍ", nameEnglish: "Wa Mā Min Dābbatin", startSurah: "Hud" },
  { number: 13, nameArabic: "وَمَاۤ اُبَرِّئُ", nameEnglish: "Wa Mā Ubarri’u", startSurah: "Yusuf" },
  { number: 14, nameArabic: "رُبَمَا", nameEnglish: "Rubamā", startSurah: "Al-Hijr" },
  { number: 15, nameArabic: "سُبۡحٰنَ الَّذِىۡۤ", nameEnglish: "Subḥāna’lladhī", startSurah: "Al-Isra" },
  { number: 16, nameArabic: "قَالَ اَ لَمۡ", nameEnglish: "Qāla Alam", startSurah: "Al-Kahf" },
  { number: 17, nameArabic: "اِقۡتَرَبَ", nameEnglish: "Iqtaraba Li’n-Nāsi", startSurah: "Al-Anbiya" },
  { number: 18, nameArabic: "قَدۡ اَفۡلَحَ", nameEnglish: "Qad Aflaḥa", startSurah: "Al-Mu'minun" },
  { number: 19, nameArabic: "وَقَالَ الَّذِيۡنَ", nameEnglish: "Wa Qāla’lladhīna", startSurah: "Al-Furqan" },
  { number: 20, nameArabic: "اَمَّنۡ خَلَقَ", nameEnglish: "Amman Khalaqa", startSurah: "An-Naml" },
  { number: 21, nameArabic: "اُتۡلُ مَاۤ اُوۡحِىَ", nameEnglish: "Utlu Mā Ūḥiya", startSurah: "Al-Ankabut" },
  { number: 22, nameArabic: "وَمَنۡ يَّقۡنُتۡ", nameEnglish: "Wa Man Yaqnut", startSurah: "Al-Ahzab" },
  { number: 23, nameArabic: "وَمَا لِىَ", nameEnglish: "Wa Mā Liya", startSurah: "Yaseen" },
  { number: 24, nameArabic: "فَمَنۡ اَظۡلَمُ", nameEnglish: "Fa-man Aẓlamu", startSurah: "Az-Zumar" },
  { number: 25, nameArabic: "اِلَيۡهِ يُرَدُّ", nameEnglish: "Ilayhi Yuraddu", startSurah: "Fussilat" },
  { number: 26, nameArabic: "حٰمٓ", nameEnglish: "Ḥā Mīm", startSurah: "Al-Ahqaf" },
  { number: 27, nameArabic: "قَالَ فَمَا خطۡبُكُمۡ", nameEnglish: "Qāla Famā Khaṭbukum", startSurah: "Adh-Dhariyat" },
  { number: 28, nameArabic: "قَدۡ سَمِعَ اللّٰهُ", nameEnglish: "Qad Samiʿa’llāhu", startSurah: "Al-Mujadila" },
  { number: 29, nameArabic: "تَبٰرَكَ الَّذِىۡ", nameEnglish: "Tabāraka’lladhī", startSurah: "Al-Mulk" },
  { number: 30, nameArabic: "عَمَّ", nameEnglish: "ʿAmma Yatasā’alūn", startSurah: "An-Naba" },
];
